# Generated by Django 4.2.2 on 2023-08-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_mngt', '0002_rename_patient_appointment_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='address',
            new_name='paddress',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='gender',
            new_name='pgender',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='mobile_no',
            new_name='pmobile_no',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='pname',
        ),
    ]
