# Generated by Django 4.2.2 on 2023-08-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_mngt', '0003_rename_address_patient_paddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
